# Github actions to build
# and push wheel files

on:
  push:
    branches:
      - main

env:
  MAJOR_VER: 3
  MINOR_VER: 0

jobs:
  build_wheel:
    runs-on: ubuntu-latest
    permissions:
      # IMPORTANT: this permission is mandatory for trusted publishing
      id-token: write
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.9
      - name: Build wheel
        run: |
          python -m pip install --user --upgrade build
          echo "$MAJOR_VER.$MINOR_VER.${{ github.run_number }}" > VERSION
          python -m build
      - name: Publish package distributions to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        if: github.ref == 'refs/heads/master'
      - name: Publish package distributions to TestPyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          repository-url: https://test.pypi.org/legacy/
      - uses: actions/upload-artifact@v3
        with:
          name: wheel
          path: dist/*.whl
